spring.application.name=demo
# URL de conexión (localhost porque el puerto 5432 está expuesto a tu máquina)
spring.datasource.url=jdbc:postgresql://localhost:5432/products_db
spring.datasource.username=admin
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de Hibernate / JPA
# update: crea o actualiza las tablas automáticamente según tus entidades @Entity
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


# Ruta para acceder a la interfaz gráfica de Swagger UI
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true

# Ruta del JSON con la especificación OpenAPI
springdoc.api-docs.path=/v3/api-docs