spring.application.name=demo
# URL de conexión (localhost porque el puerto 5432 está expuesto a tu máquina)
spring.datasource.url=jdbc:postgresql://localhost:5432/products_db
spring.datasource.username=admin
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de Hibernate / JPA
# update: crea o actualiza las tablas automáticamente según tus entidades @Entity
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect